import type { Achievement, Adventure, Quest, ShopItem } from '../types';

export const mockQuests: Quest[] = [
  {
    id: 'quest_1',
    templateId: 'template_1',
    title: 'Составь список покупок',
    description: 'Напиши 5 вещей, которые тебе нужны на неделю',
    category: 'basics',
    difficulty: 1,
    reward: 10,
    content: 'Представь, что ты идёшь в магазин. Какие 5 вещей ты купишь?',
    answerType: 'open',
    experienceReward: 10,
    date: new Date().toISOString().split('T')[0],
    completed: false,
  },
  {
    id: 'quest_2',
    templateId: 'template_2',
    title: 'Посчитай сдачу',
    description: 'Покупка стоит 73₽, ты дал 100₽. Сколько сдачи?',
    category: 'basics',
    difficulty: 1,
    reward: 5,
    content: 'Покупка 73₽, дал 100₽. Сколько сдачи?',
    answerType: 'number',
    correctAnswer: '27',
    experienceReward: 5,
    date: new Date().toISOString().split('T')[0],
    completed: false,
  },
  {
    id: 'quest_3',
    templateId: 'template_3',
    title: 'Нужно vs Хочу',
    description: 'Объясни разницу между "нужно" и "хочу" на 3 примерах',
    category: 'saving',
    difficulty: 2,
    reward: 15,
    content: 'Приведи 3 примера, когда ты покупаешь то, что "нужно", и 3 примера, когда "хочу".',
    answerType: 'open',
    experienceReward: 15,
    date: new Date().toISOString().split('T')[0],
    completed: false,
  },
];

export const mockShopItems: ShopItem[] = [
  {
    id: 'apple',
    name: 'Яблоко',
    description: 'Свежее и сочное',
    category: 'food',
    price: 5,
    effect: { hunger: 10 },
    rarity: 'common',
    image: '🍎',
    consumable: true,
  },
  {
    id: 'pizza',
    name: 'Пицца',
    description: 'Вкусная пицца',
    category: 'food',
    price: 15,
    effect: { hunger: 25 },
    rarity: 'common',
    image: '🍕',
    consumable: true,
  },
  {
    id: 'cake',
    name: 'Тортик',
    description: 'Сладкий тортик',
    category: 'food',
    price: 25,
    effect: { hunger: 40 },
    rarity: 'rare',
    image: '🍰',
    consumable: true,
  },
  {
    id: 'ball',
    name: 'Мячик',
    description: 'Весёлый мячик для игр',
    category: 'toy',
    price: 30,
    effect: { happiness: 20 },
    rarity: 'common',
    image: '🎾',
    consumable: true,
  },
  {
    id: 'teddy',
    name: 'Мишка',
    description: 'Мягкий плюшевый мишка',
    category: 'toy',
    price: 50,
    effect: { happiness: 30 },
    rarity: 'rare',
    image: '🧸',
    consumable: true,
  },
  {
    id: 'top_hat',
    name: 'Цилиндр',
    description: 'Стильный чёрный цилиндр',
    category: 'accessory',
    price: 75,
    effect: {},
    rarity: 'rare',
    image: '🎩',
    consumable: false,
    levelRequirement: 3,
  },
  {
    id: 'crown',
    name: 'Корона',
    description: 'Золотая корона с драгоценными камнями',
    category: 'accessory',
    price: 200,
    effect: {},
    rarity: 'legendary',
    image: '👑',
    consumable: false,
    levelRequirement: 7,
  },
  {
    id: 'stock',
    name: 'Акция',
    description: 'Приносит 5 монет в день',
    category: 'investment',
    price: 100,
    effect: { passiveIncome: 5 },
    rarity: 'rare',
    image: '📈',
    consumable: false,
  },
];

export const mockAchievements: Achievement[] = [
  {
    id: 'first_quest',
    title: 'Первые шаги',
    description: 'Выполни первое задание',
    icon: '🏆',
    category: 'quests',
    condition: { type: 'quests_completed', value: 1 },
    unlocked: false,
    reward: { coins: 10, experience: 5 },
  },
  {
    id: 'quest_master',
    title: 'Мастер заданий',
    description: 'Выполни 10 заданий',
    icon: '🏆',
    category: 'quests',
    condition: { type: 'quests_completed', value: 10 },
    unlocked: false,
    reward: { coins: 100, experience: 50 },
  },
  {
    id: 'saver_100',
    title: 'Копилка',
    description: 'Накопи 100 монет',
    icon: '💰',
    category: 'savings',
    condition: { type: 'savings_reached', value: 100 },
    unlocked: false,
    reward: { coins: 20, experience: 10 },
  },
  {
    id: 'streak_7',
    title: 'Неделя вместе',
    description: 'Заходи в приложение 7 дней подряд',
    icon: '🔥',
    category: 'streak',
    condition: { type: 'streak_days', value: 7 },
    unlocked: false,
    reward: { coins: 50, experience: 20 },
  },
];

export const mockAdventures: Adventure[] = [
  {
    id: 'shop_visit',
    name: 'Поход в магазин',
    description: 'Питомец изучает цены и учится выбирать выгодные покупки',
    duration: 2,
    minReward: 15,
    maxReward: 25,
    category: 'shop',
    emoji: '🏪',
    energyCost: 20,
    levelRequirement: 2,
  },
  {
    id: 'bank_visit',
    name: 'Визит в банк',
    description: 'Питомец узнаёт о вкладах и процентах',
    duration: 4,
    minReward: 30,
    maxReward: 50,
    category: 'bank',
    emoji: '🏦',
    energyCost: 20,
    levelRequirement: 4,
  },
  {
    id: 'exchange_visit',
    name: 'Поездка на биржу',
    description: 'Питомец изучает мир инвестиций',
    duration: 8,
    minReward: 60,
    maxReward: 120,
    category: 'exchange',
    emoji: '📈',
    energyCost: 20,
    levelRequirement: 6,
  },
];
